/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semester_project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Property_Show extends javax.swing.JFrame {

    /**
     * Creates new form Property_Show
     */
    public Property_Show() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_show = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNIC", "Family_Members", "Father_Status", "Father_Income", "Plots_Cost", "Vehicles", "House_Size", "Utility_Bills", "Medical_Bills", "Education_Bills", "Accomodation_Bills", "Misc_Bills"
            }
        ));
        jScrollPane1.setViewportView(jTable1_show);

        jPanel1.setBackground(new java.awt.Color(109, 192, 197));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Money Transaction");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(579, 579, 579)
                .addComponent(jLabel1)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String ucnic;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Recepient_Show(ucnic).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public Property_Show(String ycnic){
        initComponents();
        ucnic=ycnic;
        ArrayList<User> list=userList(ycnic);
        ArrayList<User2> list2=userList2(ycnic);
        DefaultTableModel model=(DefaultTableModel) jTable1_show.getModel();
        Object[] col=new Object[12];
        for (int i=0;i<1;i++){
        col[0]=list.get(i).cnic;
        col[1]=list.get(i).family_members;
        col[2]=list.get(i).father_status;
        col[3]=list.get(i).father_income;
        col[4]=list.get(i).plots_cost;
        col[5]=list.get(i).vehicles;
        col[6]=list.get(i).home_size;
        col[7]=list2.get(i).utility;
        col[8]=list2.get(i).medical;
        col[9]=list2.get(i).education;
        col[10]=list2.get(i).accomodation;
        col[11]=list2.get(i).misc;
        model.addRow(col);
        
    }  
    }
    ArrayList<User> userList(String ycnic){
        ArrayList<User> userlist=new ArrayList<>();
        try{
        Connection con = Semester_Project.connectDB("JDBC:sqlite:Property_Info.db");
            String q="SELECT * FROM Property_Info WHERE CNIC=?";
            PreparedStatement ps=con.prepareStatement(q);
            ps.setString(1,ycnic);
            ps.execute();
            ResultSet rs=ps.executeQuery();
            User user;
            while (rs.next()){
                user=new User(rs.getString("CNIC"),rs.getString("Family_Members"),rs.getString("Father_Status"),rs.getString("Father_Income"),
                        rs.getString("Plots_Cost"),rs.getString("Vehicles"),rs.getString("House_Size"));
                userlist.add(user);
            
            } } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        return userlist;
    }
    ArrayList<User2> userList2(String ycnic){
        ArrayList<User2> userlist=new ArrayList<>();
        try{
        Connection con = Semester_Project.connectDB("JDBC:sqlite:Expenditures.db");
            String q="SELECT * FROM Expenditures WHERE CNIC=?";
            PreparedStatement ps=con.prepareStatement(q);
            ps.setString(1,ycnic);
            ps.execute();
            ResultSet rs=ps.executeQuery();
            User2 user;
            while (rs.next()){
                user=new User2(rs.getString("Utility"),rs.getString("Medical"),rs.getString("Education"),
                        rs.getString("Accomodation"),rs.getString("Miscellaneous"));
                userlist.add(user);
            
            } } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        return userlist;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Property_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Property_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Property_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Property_Show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Property_Show().setVisible(true);
            }
        });
    }
private static class User {
         String family_members,father_status,father_income,plots_cost,vehicles,home_size,cnic;
        public User(String cnic,String family_members,String father_status,String father_income,String plots_cost,String vehicles,
                String home_size) {
            this.family_members=family_members;
            this.father_status=father_status;
            this.father_income=father_income;
            this.plots_cost=plots_cost;
            this.vehicles=vehicles;
            this.home_size=home_size;
            this.cnic=cnic;
        }
 }
private static class User2 {
         String utility,medical,education,accomodation,misc;
        public User2(String utility,String medical,String education,String accomodation,String misc) {
            this.utility=utility;
            this.medical=medical;
            this.education=education;
            this.accomodation=accomodation;
            this.misc=misc;
        }
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_show;
    // End of variables declaration//GEN-END:variables
}
